# The title of the website, if left empty this will default to the repository name
# title: Foundation For Public Code

# Jekyll plugins that are supported by GitHub pages
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji

# Also render the README to HTML even if there is an index.md
include:
  - README.md

# Use the Foundation For Public Code Jekyll theme`
remote_theme: publiccodenet/jekyll-theme
